# Rinako reference config
# Please make a copy of this file called config.toml with your desired settings.

# Auth token: get this from discord developer portal, Create an app, make a bot for it, then get its token
auth_token = "some_auth_token"

# Discriminator: what determines the bot commands. Defaults to `>`
discriminator = ">"

# Role channel determines where roles can be set. 
role_channel = "123154120501250"

# Color determines the color of Rinako's embeds.
color = "EE73B8"

db_path = "resources/db.sqlite3"

# Allowed roles: Which roles users are allowed to set. Please choose these carefully.
[[allowed_roles]]
role = "Rina Oshi"
desc = "Grants access to the #rina-chan board"

[[allowed_roles]]
role = "notAnAdminRole"
desc = "Grants access to no role in particular"